version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: sumrise_app
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - internal
    depends_on:
      - pocketbase
    env_file:
      - .env


  pocketbase: 
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    container_name: pocketbase
    ports:
      - "8080:8080"
    volumes:
      - ./pocketbase/data:/pb_data
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_hooks:/pb/pb_hooks
    networks:
      - internal
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/ssl/certs:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - internal
    depends_on:
      - app
      - pocketbase

networks:
  internal:
    driver: bridge
